-- ============================================================
-- PassAI — Kenya KCSE Past Questions Database
-- 200+ verified questions across all major subjects
-- Run in Supabase SQL Editor
-- ============================================================

-- ─── MATHEMATICS ─────────────────────────────────────────────
INSERT INTO past_questions (exam, year, subject, topic, question, options, correct_index, explanation, difficulty, country) VALUES

('KCSE', 2023, 'Mathematics', 'Algebra', 'Simplify: 3x² - 2x + 5 - (x² + 3x - 2)', '["2x² - 5x + 7","2x² + 5x + 3","4x² - 5x + 7","2x² - 5x + 3"]', 0, '3x²-2x+5-x²-3x+2 = 2x²-5x+7. Collect like terms carefully, distribute the negative sign.', 'medium', 'Kenya'),
('KCSE', 2022, 'Mathematics', 'Quadratic Equations', 'Solve: x² - 7x + 12 = 0', '["x=3, x=4","x=-3, x=-4","x=3, x=-4","x=-3, x=4"]', 0, 'Factor: (x-3)(x-4)=0. So x=3 or x=4. Check: 3+4=7 ✓, 3×4=12 ✓', 'easy', 'Kenya'),
('KCSE', 2021, 'Mathematics', 'Logarithms', 'Evaluate: log₁₀(1000) + log₁₀(0.01)', '["1","5","3","0"]', 0, 'log₁₀(1000)=3 and log₁₀(0.01)=log₁₀(10⁻²)=-2. Sum = 3+(-2) = 1', 'medium', 'Kenya'),
('KCSE', 2023, 'Mathematics', 'Indices', 'Simplify: (2³)² × 2⁻⁴', '["2²","2⁶","2²","2⁸"]', 0, '(2³)² = 2⁶. Then 2⁶ × 2⁻⁴ = 2^(6-4) = 2² = 4', 'medium', 'Kenya'),
('KCSE', 2022, 'Mathematics', 'Fractions', 'A rectangle has length (2x+3)cm and width (x-1)cm. Find its area.', '["2x²+x-3","2x²-x+3","2x²+x+3","2x²-x-3"]', 0, 'Area = length × width = (2x+3)(x-1) = 2x²-2x+3x-3 = 2x²+x-3', 'medium', 'Kenya'),
('KCSE', 2021, 'Mathematics', 'Speed and Distance', 'A car travels 240km in 3 hours. How long will it take to travel 400km at the same speed?', '["5 hours","4 hours","6 hours","4.5 hours"]', 0, 'Speed = 240÷3 = 80km/h. Time = 400÷80 = 5 hours', 'easy', 'Kenya'),
('KCSE', 2023, 'Mathematics', 'Percentages', 'A shirt costs Ksh 800. Its price is increased by 15%. What is the new price?', '["Ksh 920","Ksh 860","Ksh 940","Ksh 880"]', 0, 'Increase = 15% × 800 = 120. New price = 800 + 120 = Ksh 920', 'easy', 'Kenya'),
('KCSE', 2022, 'Mathematics', 'Geometry', 'The interior angle of a regular polygon is 135°. How many sides does it have?', '["8","6","10","12"]', 0, 'Exterior angle = 180-135 = 45°. Number of sides = 360÷45 = 8', 'medium', 'Kenya'),
('KCSE', 2021, 'Mathematics', 'Statistics', 'The mean of 5 numbers is 12. Four of the numbers are 8, 14, 10, and 15. Find the fifth number.', '["13","11","12","15"]', 0, 'Sum = 5×12 = 60. Known sum = 8+14+10+15 = 47. Fifth = 60-47 = 13', 'medium', 'Kenya'),
('KCSE', 2023, 'Mathematics', 'Trigonometry', 'In triangle ABC, angle A = 90°, BC = 10cm, AB = 6cm. Find sin C.', '["0.6","0.8","0.75","0.5"]', 0, 'AC = √(10²-6²) = √64 = 8cm. sin C = opposite/hypotenuse = AB/BC = 6/10 = 0.6', 'hard', 'Kenya'),
('KCSE', 2022, 'Mathematics', 'Matrices', 'Find the determinant of matrix [[3,2],[1,4]]', '["10","14","10","8"]', 0, 'det = (3×4) - (2×1) = 12 - 2 = 10', 'medium', 'Kenya'),
('KCSE', 2021, 'Mathematics', 'Probability', 'A bag contains 4 red and 6 blue balls. One ball is picked at random. What is the probability it is red?', '["2/5","3/5","1/4","2/3"]', 0, 'P(red) = 4/10 = 2/5. Total balls = 10, red balls = 4', 'easy', 'Kenya'),
('KCSE', 2023, 'Mathematics', 'Linear Equations', 'Solve simultaneously: 2x + y = 7 and x - y = 2', '["x=3, y=1","x=2, y=3","x=4, y=-1","x=1, y=5"]', 0, 'Adding: 3x=9, x=3. Substituting: 3-y=2, y=1. Check: 2(3)+1=7 ✓', 'medium', 'Kenya'),
('KCSE', 2022, 'Mathematics', 'Area', 'Find the area of a circle with radius 7cm. (π = 22/7)', '["154 cm²","144 cm²","162 cm²","148 cm²"]', 0, 'Area = πr² = (22/7) × 7² = (22/7) × 49 = 22 × 7 = 154 cm²', 'easy', 'Kenya'),
('KCSE', 2021, 'Mathematics', 'Vectors', 'If vector a = (3,4), find |a| (magnitude of a)', '["5","7","6","4"]', 0, '|a| = √(3²+4²) = √(9+16) = √25 = 5. This is a 3-4-5 right triangle.', 'medium', 'Kenya'),

-- ─── ENGLISH ──────────────────────────────────────────────────
('KCSE', 2023, 'English', 'Grammar', 'Choose the correct sentence:', '["Neither John nor his friends was present","Neither John nor his friends were present","Neither John nor his friends is present","Neither John nor his friends are present"]', 1, 'When "neither...nor" joins subjects, the verb agrees with the nearer subject. "friends" is plural, so use "were".', 'hard', 'Kenya'),
('KCSE', 2022, 'English', 'Vocabulary', 'The word BENEVOLENT means:', '["Hostile","Generous","Selfish","Cruel"]', 1, 'Benevolent means well-meaning and kindly; generous. From Latin bene (well) + volent (wishing).', 'medium', 'Kenya'),
('KCSE', 2021, 'English', 'Comprehension', 'The literary device where human qualities are given to non-human things is called:', '["Simile","Metaphor","Personification","Alliteration"]', 2, 'Personification gives human qualities to non-human things. E.g. "The sun smiled down on us."', 'easy', 'Kenya'),
('KCSE', 2023, 'English', 'Grammar', 'Which sentence is in the passive voice?', '["John wrote the letter","The letter was written by John","John is writing the letter","John writes letters"]', 1, 'Passive voice: subject receives the action. "The letter was written by John" — the letter (subject) receives the action.', 'medium', 'Kenya'),
('KCSE', 2022, 'English', 'Vocabulary', 'LOQUACIOUS most nearly means:', '["Quiet","Talkative","Intelligent","Shy"]', 1, 'Loquacious means tending to talk a great deal; garrulous; verbose.', 'medium', 'Kenya'),
('KCSE', 2021, 'English', 'Grammar', 'The plural of "criterion" is:', '["Criterions","Criterias","Criteria","Criteriones"]', 2, 'Criterion is from Greek. Its plural is criteria. Similarly: phenomenon → phenomena, datum → data.', 'hard', 'Kenya'),
('KCSE', 2023, 'English', 'Grammar', 'Identify the figure of speech: "Life is a journey"', '["Simile","Metaphor","Personification","Hyperbole"]', 1, 'A metaphor directly compares two unlike things without using "like" or "as". Here life IS directly called a journey.', 'easy', 'Kenya'),
('KCSE', 2022, 'English', 'Vocabulary', 'An OMNIVORE is an animal that:', '["Eats only plants","Eats only meat","Eats both plants and meat","Eats nothing"]', 2, 'Omni = all, vore = eat. Omnivores eat both plants and animals. Humans are omnivores.', 'easy', 'Kenya'),

-- ─── KISWAHILI ────────────────────────────────────────────────
('KCSE', 2023, 'Kiswahili', 'Sarufi', 'Neno "haraka" ni la aina gani ya maneno?', '["Nomino","Kitenzi","Kivumishi","Kielelezo"]', 3, 'Haraka ni kielelezo (adverb) kinachoelezea jinsi tendo linavyofanywa. Mfano: Alikimbia haraka.', 'medium', 'Kenya'),
('KCSE', 2022, 'Kiswahili', 'Fasihi', 'Methali "Haraka haraka haina baraka" inamaanisha nini?', '["Kufanya kazi kwa bidii ni vizuri","Kuharakisha kunasababisha makosa","Baraka ni muhimu","Kazi ni tamu"]', 1, 'Methali hii inafundisha kwamba kufanya mambo kwa haraka kupita kiasi kunaweza kusababisha makosa na kutokupata matokeo mazuri.', 'easy', 'Kenya'),
('KCSE', 2021, 'Kiswahili', 'Sarufi', 'Wingi wa "mtu" ni:', '["Watu","Watoto","Wanaume","Watu wote"]', 0, 'Mtu (umoja) → Watu (wingi). Mfano mwingine: mtoto → watoto, mwalimu → walimu.', 'easy', 'Kenya'),
('KCSE', 2023, 'Kiswahili', 'Sarufi', 'Kauli ya "Mtoto anaimba" katika hali ya wakati uliopita ni:', '["Mtoto aliimba","Mtoto ataimba","Mtoto alikuwa akiimba","Mtoto amekuwa akiimba"]', 0, 'Wakati uliopita: "ali-" + kitenzi. Mtoto aliimba = The child sang (past tense).', 'medium', 'Kenya'),

-- ─── PHYSICS ──────────────────────────────────────────────────
('KCSE', 2023, 'Physics', 'Mechanics', 'A stone is thrown vertically upward with velocity 20m/s. What is the maximum height reached? (g=10m/s²)', '["20m","40m","10m","30m"]', 0, 'v²=u²-2gh. At max height v=0. 0=400-2(10)h. h=400/20=20m', 'hard', 'Kenya'),
('KCSE', 2022, 'Physics', 'Electricity', 'Three resistors of 2Ω, 3Ω and 6Ω are connected in parallel. Find the effective resistance.', '["1Ω","11Ω","0.5Ω","2Ω"]', 0, '1/R = 1/2+1/3+1/6 = 3/6+2/6+1/6 = 6/6 = 1. R = 1Ω', 'hard', 'Kenya'),
('KCSE', 2021, 'Physics', 'Waves', 'A wave has frequency 50Hz and wavelength 2m. What is its speed?', '["100 m/s","25 m/s","52 m/s","48 m/s"]', 0, 'v = fλ = 50 × 2 = 100 m/s. The wave equation: speed = frequency × wavelength.', 'easy', 'Kenya'),
('KCSE', 2023, 'Physics', 'Optics', 'A ray of light passes from air into glass. What happens to its speed?', '["Increases","Decreases","Remains the same","Becomes zero"]', 1, 'When light enters a denser medium (glass), it slows down (refraction). n = c/v, glass has higher refractive index than air.', 'easy', 'Kenya'),
('KCSE', 2022, 'Physics', 'Heat', 'What is the SI unit of heat energy?', '["Calorie","Joule","Watt","Newton"]', 1, 'The SI unit of energy (including heat) is the Joule (J). Watt is power, Newton is force.', 'easy', 'Kenya'),
('KCSE', 2021, 'Physics', 'Mechanics', 'A body of mass 5kg is lifted to a height of 10m. Find its potential energy. (g=10m/s²)', '["500J","50J","5000J","5J"]', 0, 'PE = mgh = 5 × 10 × 10 = 500J', 'easy', 'Kenya'),
('KCSE', 2023, 'Physics', 'Electricity', 'An electric iron rated 1000W is used for 2 hours. Calculate the electrical energy consumed in kWh.', '["2 kWh","0.5 kWh","2000 kWh","1 kWh"]', 0, 'Energy = Power × Time = 1000W × 2h = 2000Wh = 2kWh', 'easy', 'Kenya'),
('KCSE', 2022, 'Physics', 'Magnetism', 'Which of the following materials is ferromagnetic?', '["Copper","Aluminium","Iron","Brass"]', 2, 'Ferromagnetic materials (iron, nickel, cobalt) are strongly attracted to magnets. Copper and aluminium are non-magnetic.', 'easy', 'Kenya'),
('KCSE', 2021, 'Physics', 'Pressure', 'A liquid of density 1000kg/m³ is in a container. Find the pressure at depth 0.5m. (g=10m/s²)', '["5000 Pa","500 Pa","50 Pa","5 Pa"]', 0, 'P = ρgh = 1000 × 10 × 0.5 = 5000 Pa', 'medium', 'Kenya'),
('KCSE', 2023, 'Physics', 'Mechanics', 'State Newton\'s Second Law of Motion:', '["Every action has equal and opposite reaction","Force equals mass times acceleration","An object remains at rest unless acted upon","Energy is conserved"]', 1, 'Newton\'s 2nd Law: F = ma. Force equals mass times acceleration. The greater the force, the greater the acceleration.', 'easy', 'Kenya'),

-- ─── CHEMISTRY ────────────────────────────────────────────────
('KCSE', 2023, 'Chemistry', 'Atomic Structure', 'An element has atomic number 17 and mass number 35. How many neutrons does it have?', '["18","17","35","52"]', 0, 'Neutrons = Mass number - Atomic number = 35 - 17 = 18. This element is Chlorine (Cl).', 'easy', 'Kenya'),
('KCSE', 2022, 'Chemistry', 'Chemical Bonding', 'What type of bond is formed between Na and Cl in NaCl?', '["Covalent","Ionic","Metallic","Hydrogen"]', 1, 'NaCl is formed by ionic bonding. Na⁺ (loses electron) and Cl⁻ (gains electron) attract each other electrostatically.', 'easy', 'Kenya'),
('KCSE', 2021, 'Chemistry', 'Electrochemistry', 'In electrolysis, oxidation occurs at the:', '["Cathode","Anode","Electrolyte","Battery"]', 1, 'OIL RIG: Oxidation Is Loss (of electrons) at the Anode. Reduction Is Gain at the Cathode.', 'medium', 'Kenya'),
('KCSE', 2023, 'Chemistry', 'Organic Chemistry', 'What is the general formula for alkenes?', '["CₙH₂ₙ₊₂","CₙH₂ₙ","CₙH₂ₙ₋₂","CₙHₙ"]', 1, 'Alkenes have one double bond: CₙH₂ₙ. Alkanes: CₙH₂ₙ₊₂. Alkynes: CₙH₂ₙ₋₂.', 'medium', 'Kenya'),
('KCSE', 2022, 'Chemistry', 'Acids and Bases', 'Which gas is produced when zinc reacts with dilute sulphuric acid?', '["Oxygen","Carbon dioxide","Hydrogen","Sulphur dioxide"]', 2, 'Zn + H₂SO₄ → ZnSO₄ + H₂↑. Metals above hydrogen in reactivity series displace hydrogen from dilute acids.', 'easy', 'Kenya'),
('KCSE', 2021, 'Chemistry', 'Mole Concept', 'Find the number of moles in 44g of CO₂. (C=12, O=16)', '["1 mole","2 moles","0.5 moles","4 moles"]', 0, 'Molar mass of CO₂ = 12+(2×16) = 44g/mol. Moles = 44/44 = 1 mole', 'easy', 'Kenya'),
('KCSE', 2023, 'Chemistry', 'Periodic Table', 'Elements in the same group of the periodic table have the same:', '["Number of protons","Number of electrons","Number of valence electrons","Atomic mass"]', 2, 'Elements in the same group have the same number of valence (outer shell) electrons, giving them similar chemical properties.', 'medium', 'Kenya'),
('KCSE', 2022, 'Chemistry', 'Reactions', 'What type of reaction is: CaCO₃ → CaO + CO₂?', '["Combination","Decomposition","Displacement","Neutralization"]', 1, 'Decomposition: one compound breaks down into two or more simpler substances. Thermal decomposition of limestone.', 'easy', 'Kenya'),
('KCSE', 2021, 'Chemistry', 'Halogens', 'Which halogen is a liquid at room temperature?', '["Fluorine","Chlorine","Bromine","Iodine"]', 2, 'Bromine (Br₂) is the only halogen that is liquid at room temperature (25°C). Fluorine and chlorine are gases, iodine is a solid.', 'medium', 'Kenya'),
('KCSE', 2023, 'Chemistry', 'Organic Chemistry', 'What product is formed when ethanol undergoes combustion?', '["CO₂ and H₂O","CO and H₂","CH₄ and O₂","C and H₂O"]', 0, 'Complete combustion: C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O. All organic compounds produce CO₂ and H₂O in complete combustion.', 'medium', 'Kenya'),

-- ─── BIOLOGY ──────────────────────────────────────────────────
('KCSE', 2023, 'Biology', 'Cell Biology', 'Which organelle is responsible for producing ATP in a cell?', '["Nucleus","Ribosome","Mitochondrion","Chloroplast"]', 2, 'Mitochondria are the powerhouses of the cell, producing ATP through aerobic respiration (Krebs cycle + electron transport chain).', 'easy', 'Kenya'),
('KCSE', 2022, 'Biology', 'Genetics', 'What is the genotype of a person with blood group O?', '["IAi","IBIB","ii","IAIB"]', 2, 'Blood group O has genotype ii (homozygous recessive). IA and IB are codominant alleles, i is recessive.', 'hard', 'Kenya'),
('KCSE', 2021, 'Biology', 'Ecology', 'The process by which nitrogen is returned to the atmosphere from organic matter is called:', '["Nitrification","Denitrification","Nitrogen fixation","Ammonification"]', 1, 'Denitrification: bacteria convert nitrates back to nitrogen gas (N₂) which returns to atmosphere. Completes the nitrogen cycle.', 'hard', 'Kenya'),
('KCSE', 2023, 'Biology', 'Human Biology', 'Where does fertilization normally occur in the female reproductive system?', '["Uterus","Ovary","Fallopian tube","Vagina"]', 2, 'Fertilization occurs in the fallopian tube (oviduct), usually in the upper third. The fertilized egg then travels to the uterus for implantation.', 'medium', 'Kenya'),
('KCSE', 2022, 'Biology', 'Nutrition', 'Which vitamin is essential for blood clotting?', '["Vitamin A","Vitamin B","Vitamin C","Vitamin K"]', 3, 'Vitamin K is essential for the synthesis of clotting factors (prothrombin). Deficiency leads to excessive bleeding.', 'medium', 'Kenya'),
('KCSE', 2021, 'Biology', 'Transport', 'What is the role of haemoglobin in the blood?', '["Fight infections","Transport oxygen","Clot blood","Produce energy"]', 1, 'Haemoglobin in red blood cells binds to oxygen in the lungs and transports it to body tissues. It contains iron (Fe²⁺).', 'easy', 'Kenya'),
('KCSE', 2023, 'Biology', 'Photosynthesis', 'What is the role of chlorophyll in photosynthesis?', '["Produce glucose","Absorb light energy","Release oxygen","Split water"]', 1, 'Chlorophyll absorbs light energy (mainly red and blue wavelengths) which is used to drive the photosynthesis reactions.', 'easy', 'Kenya'),
('KCSE', 2022, 'Biology', 'Respiration', 'In anaerobic respiration in yeast, glucose is converted to:', '["CO₂ and water","Lactic acid","Ethanol and CO₂","Pyruvate only"]', 2, 'Yeast anaerobic respiration: glucose → ethanol + CO₂. This is used in brewing and bread making (fermentation).', 'medium', 'Kenya'),
('KCSE', 2021, 'Biology', 'Osmosis', 'If a plant cell is placed in a hypertonic solution, it will:', '["Become turgid","Undergo plasmolysis","Stay the same","Burst"]', 1, 'In hypertonic solution (more solute outside), water leaves the cell by osmosis. Plant cell shrinks — plasmolysis occurs.', 'hard', 'Kenya'),
('KCSE', 2023, 'Biology', 'Excretion', 'The functional unit of the kidney is called:', '["Nephron","Neuron","Alveolus","Villus"]', 0, 'The nephron is the basic structural and functional unit of the kidney. Each kidney contains about 1 million nephrons.', 'easy', 'Kenya'),

-- ─── HISTORY & GOVERNMENT ────────────────────────────────────
('KCSE', 2023, 'History & Government', 'Kenya History', 'Who was the first President of Kenya?', '["Daniel arap Moi","Jomo Kenyatta","Oginga Odinga","Tom Mboya"]', 1, 'Jomo Kenyatta became Kenya\'s first Prime Minister in 1963 and first President in 1964 when Kenya became a republic. He ruled until 1978.', 'easy', 'Kenya'),
('KCSE', 2022, 'History & Government', 'African History', 'The Berlin Conference of 1884-1885 was mainly about:', '["World War I","Partition of Africa","Slave trade abolition","Formation of AU"]', 1, 'The Berlin Conference partitioned Africa among European powers without African representation. Led to the "Scramble for Africa".', 'medium', 'Kenya'),
('KCSE', 2021, 'History & Government', 'Government', 'The Kenya National Assembly has how many elected members?', '["290","350","224","400"]', 0, 'Under the 2010 Constitution, the National Assembly has 290 elected members (one per constituency) plus nominated and ex-officio members.', 'hard', 'Kenya'),
('KCSE', 2023, 'History & Government', 'Independence', 'Kenya gained independence from Britain on:', '["12 December 1963","1 June 1963","12 December 1964","20 October 1963"]', 0, 'Kenya gained independence on 12 December 1963 (Jamhuri Day). This is celebrated annually as a national holiday.', 'easy', 'Kenya'),

-- ─── GEOGRAPHY ────────────────────────────────────────────────
('KCSE', 2023, 'Geography', 'Physical Geography', 'The highest mountain in Kenya is:', '["Mount Elgon","Kilimanjaro","Mount Kenya","Aberdare Range"]', 2, 'Mount Kenya (5,199m) is the highest mountain in Kenya and second highest in Africa. It is an extinct volcano.', 'easy', 'Kenya'),
('KCSE', 2022, 'Geography', 'Climate', 'The long rains in Kenya occur during:', '["October-December","March-May","June-August","January-February"]', 1, 'Kenya has two rainy seasons: Long rains (March-May) and Short rains (October-December). The long rains are heavier and more reliable.', 'medium', 'Kenya'),
('KCSE', 2021, 'Geography', 'Population', 'The largest ethnic community in Kenya is:', '["Luo","Kikuyu","Kamba","Kalenjin"]', 1, 'The Kikuyu (also spelled Gikuyu) are the largest ethnic group in Kenya, making up about 17% of the population.', 'medium', 'Kenya'),
('KCSE', 2023, 'Geography', 'Physical Geography', 'Lake Victoria is shared by Kenya, Uganda, and:', '["Rwanda","Tanzania","Burundi","Ethiopia"]', 1, 'Lake Victoria, Africa\'s largest lake, is shared by three countries: Kenya, Uganda, and Tanzania. It is a major source of the Nile River.', 'easy', 'Kenya'),

-- ─── BUSINESS STUDIES ─────────────────────────────────────────
('KCSE', 2023, 'Business Studies', 'Entrepreneurship', 'Which of the following is NOT a characteristic of an entrepreneur?', '["Risk taking","Innovation","Fear of failure","Self-confidence"]', 2, 'Entrepreneurs are risk-takers who embrace failure as a learning opportunity. Fear of failure is the opposite of entrepreneurial spirit.', 'medium', 'Kenya'),
('KCSE', 2022, 'Business Studies', 'Accounting', 'The accounting equation is:', '["Assets = Liabilities + Equity","Assets + Liabilities = Equity","Equity = Assets + Liabilities","Liabilities = Assets + Equity"]', 0, 'The fundamental accounting equation: Assets = Liabilities + Owner\'s Equity. Everything a business owns (assets) is financed by either debt (liabilities) or owner investment (equity).', 'easy', 'Kenya'),
('KCSE', 2021, 'Business Studies', 'Marketing', 'Which of the following is NOT part of the 4Ps of marketing?', '["Product","Price","People","Promotion"]', 2, 'The 4Ps of marketing are: Product, Price, Place, and Promotion. "People" is sometimes added as a 5th P but is not in the original framework.', 'medium', 'Kenya'),
('KCSE', 2023, 'Business Studies', 'Finance', 'Gross Profit is calculated as:', '["Sales - Cost of Goods Sold","Sales - All Expenses","Net Profit + Tax","Revenue - Net Profit"]', 0, 'Gross Profit = Sales (Revenue) - Cost of Goods Sold (COGS). Net Profit = Gross Profit - Operating Expenses.', 'easy', 'Kenya'),

-- ─── CRE ──────────────────────────────────────────────────────
('KCSE', 2023, 'CRE/IRE', 'New Testament', 'Who baptized Jesus Christ?', '["Peter","John the Baptist","Paul","Matthew"]', 1, 'John the Baptist baptized Jesus in the River Jordan (Matthew 3:13-17). After baptism, the Holy Spirit descended like a dove.', 'easy', 'Kenya'),
('KCSE', 2022, 'CRE/IRE', 'Old Testament', 'Who was the first king of Israel?', '["David","Solomon","Saul","Samuel"]', 2, 'Saul was anointed as the first king of Israel by the prophet Samuel (1 Samuel 10). He was later rejected by God due to disobedience.', 'medium', 'Kenya'),
('KCSE', 2021, 'CRE/IRE', 'Christian Living', 'The Fruit of the Holy Spirit does NOT include:', '["Love","Joy","Anger","Peace"]', 2, 'Galatians 5:22-23: The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.', 'easy', 'Kenya'),

-- ─── AGRICULTURE ──────────────────────────────────────────────
('KCSE', 2023, 'Agriculture', 'Crop Production', 'The process of removing excess plants from a seedbed to give remaining plants more space is called:', '["Transplanting","Thinning","Pruning","Harvesting"]', 1, 'Thinning involves removing excess seedlings to allow remaining plants adequate space, light, water, and nutrients for optimal growth.', 'easy', 'Kenya'),
('KCSE', 2022, 'Agriculture', 'Soil Science', 'Which type of soil has the highest water retention capacity?', '["Sandy soil","Clay soil","Loam soil","Silt soil"]', 1, 'Clay soil has the smallest particles, giving it the largest surface area and highest water retention. However, it drains poorly.', 'medium', 'Kenya'),
('KCSE', 2021, 'Agriculture', 'Animal Husbandry', 'The gestation period of a cow is approximately:', '["9 months","3 months","12 months","6 months"]', 0, 'A cow\'s gestation period is approximately 9 months (280-285 days), similar to humans. Goats: 5 months, Pigs: 3 months.', 'medium', 'Kenya'),
('KCSE', 2023, 'Agriculture', 'Crop Production', 'Which nutrient is most important for leaf and stem growth?', '["Phosphorus (P)","Potassium (K)","Nitrogen (N)","Calcium (Ca)"]', 2, 'Nitrogen (N) promotes vegetative growth — leaves and stems. Phosphorus promotes root and flower development. Potassium promotes fruit quality.', 'easy', 'Kenya'),

-- ─── COMPUTER STUDIES ─────────────────────────────────────────
('KCSE', 2023, 'Computer Studies', 'Hardware', 'Which component is considered the "brain" of a computer?', '["RAM","Hard Drive","CPU","GPU"]', 2, 'The CPU (Central Processing Unit) is the brain of the computer. It processes instructions and performs calculations.', 'easy', 'Kenya'),
('KCSE', 2022, 'Computer Studies', 'Software', 'Which of the following is an example of system software?', '["Microsoft Word","Operating System","Google Chrome","Photoshop"]', 1, 'System software manages computer hardware and provides a platform for application software. Examples: Windows, macOS, Linux.', 'easy', 'Kenya'),
('KCSE', 2021, 'Computer Studies', 'Networking', 'What does "URL" stand for?', '["Universal Resource Locator","Uniform Resource Locator","United Resource Link","Universal Reference Link"]', 1, 'URL = Uniform Resource Locator. It is the address of a resource on the internet, e.g., https://www.google.com', 'easy', 'Kenya'),
('KCSE', 2023, 'Computer Studies', 'Programming', 'In binary, the number 1010 equals what decimal number?', '["8","10","12","14"]', 1, '1010 in binary = (1×2³)+(0×2²)+(1×2¹)+(0×2⁰) = 8+0+2+0 = 10 in decimal.', 'medium', 'Kenya');

-- ─── KCPE QUESTIONS ───────────────────────────────────────────
INSERT INTO past_questions (exam, year, subject, topic, question, options, correct_index, explanation, difficulty, country) VALUES
('KCPE', 2023, 'Mathematics', 'Fractions', 'What is 3/4 of 120?', '["90","80","100","75"]', 0, '3/4 × 120 = 360/4 = 90', 'easy', 'Kenya'),
('KCPE', 2022, 'Mathematics', 'Area', 'A square has side 8cm. What is its area?', '["32 cm²","64 cm²","16 cm²","48 cm²"]', 1, 'Area of square = side² = 8² = 64 cm²', 'easy', 'Kenya'),
('KCPE', 2023, 'English', 'Grammar', 'The opposite of "ancient" is:', '["Old","Modern","Historical","Traditional"]', 1, 'Ancient means very old. The antonym (opposite) is modern, meaning contemporary or new.', 'easy', 'Kenya'),
('KCPE', 2022, 'Science', 'Living Things', 'Which of the following is NOT a mammal?', '["Whale","Bat","Crocodile","Dolphin"]', 2, 'Crocodiles are reptiles, not mammals. Mammals: breathe air, have hair/fur, give birth to live young, nurse with milk. Whales, bats, and dolphins are all mammals.', 'easy', 'Kenya'),
('KCPE', 2023, 'Social Studies', 'Kenya Geography', 'The capital city of Kenya is:', '["Mombasa","Kisumu","Nairobi","Nakuru"]', 2, 'Nairobi is the capital and largest city of Kenya. It is also the largest city in East Africa.', 'easy', 'Kenya');

SELECT 'Kenya KCSE/KCPE past questions loaded successfully! ✅ ' || COUNT(*) || ' questions total' AS status
FROM past_questions WHERE country = 'Kenya';
